services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: telcoguard
      POSTGRES_PASSWORD: telcoguard_password
      POSTGRES_DB: telcoguard_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
